spring:
  application:
    name: EM-TEST

  datasource:
    url: jdbc:postgresql://postgres:5432/bankcards
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: yourSuperSecretKeyForJWTGeneration1234567890
  access-expiration-ms: 900000          # 15 минут
  refresh-expiration-ms: 604800000      # 7 дней

encryption:
  key: 1234567890ABCDEF

server:
  port: 8080