#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

spring:
  application:
    name: EM-TEST

  datasource:
    url: jdbc:postgresql://postgres:5432/bankcards
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080